package com.proiect_kafka_redis.proiect_kafka_redis.kafka;

import java.time.LocalDate;

import org.quartz.Job;
import org.quartz.JobExecutionContext;
import org.springframework.beans.factory.annotation.Autowired;

public class KafkaEventJob implements Job {

	@Autowired
	private EventProducer eventProd;
	
	public void execute(JobExecutionContext context) {
		KafkaEvent event = new KafkaEvent("Event generated by Quartz", "test", "1 PM");
		
		eventProd.sendEvent(event);
		
		System.out.println("Kafka event sent by Quartz");
	}
	
}
